Extend app installation routine

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -12,12 +12,14 @@ source "$DOTFILES/shell/helpers"
 # $DOTFILES_REMOTE      = Name of the remote git repository.
 # $INSTALL_NPM_PACKAGES = Install list of npm packages
 # $INSTALL_FORMULAE     = Install list of hombrew formulae
+# $INSTALL_APPS         = Install macOS applications
 # $CREATE_SYMLINKS      = Create symbolic links to dotfiles
 # $UPDATE_SUBMODULES    = Whether to update submodules or not
 #
 
 INSTALL_NPM_PACKAGES=0
 INSTALL_FORMULAE=0
+INSTALL_APPS=0
 CREATE_SYMLINKS=0
 UPDATE_OSX_SETTINGS=0
 
@@ -72,6 +74,7 @@ parse_options() {
           CREATE_SYMLINKS=1
           INSTALL_FORMULAE=1
           INSTALL_NPM_PACKAGES=1
+          INSTALL_APPS=1
           ;;
       ?*) print_error "Unknown option."
           usage
@@ -354,8 +357,6 @@ install_homebrew_formulae() {
   fi
 
   brew doctor
-  brew tap caskroom/cask
-  brew tap caskroom/fonts
   brew tap homebrew/php
   brew tap homebrew/dupes
   brew tap homebrew/fuse
@@ -407,39 +408,6 @@ install_homebrew_formulae() {
   brew install the_silver_searcher
   brew install ctags
 
-  # Install macOS applications via CASK
-  brew cask install --appdir="~/Applications" 1password
-  brew cask install --appdir="~/Applications" alfred
-  brew cask install --appdir="~/Applications" bartender
-  brew cask install --appdir="~/Applications" dropbox
-  brew cask install --appdir="~/Applications" firefox
-  brew cask install --appdir="~/Applications" fluid
-  brew cask install --appdir="~/Applications" google-chrome
-  brew cask install --appdir="~/Applications" hazel
-  brew cask install --appdir="~/Applications" imagealpha
-  brew cask install --appdir="~/Applications" imageoptim
-  brew cask install --appdir="~/Applications" jadengeller-helium
-  brew cask install --appdir="~/Applications" mountain
-  brew cask install --appdir="~/Applications" slack
-  brew cask install --appdir="~/Applications" spotify
-  brew cask install --appdir="~/Applications" the-unarchiver
-  brew cask install --appdir="~/Applications" transmission
-  brew cask install --appdir="~/Applications" viscosity
-  brew cask install --appdir="~/Applications" visual-studio-code
-  brew cask install virtualbox
-
-  # Improve quicklook
-  brew cask install qlcolorcode
-  brew cask install qlmarkdown
-  brew cask install qlstephen
-
-  # Install some additional fonts
-  brew cask install font-open-sans
-  brew cask install font-camingocode
-  brew cask install font-source-code-pro
-  brew cask install skyfonts
-  find /usr/local/Caskroom/skyfonts -type d -name SkyFonts.app -exec open {} \;
-
   # Install version manager for node and ruby
   brew install rbenv
   rbenv install 2.3.1
@@ -449,7 +417,6 @@ install_homebrew_formulae() {
   nodenv global 5.12.0
 
   brew cleanup
-  brew cask cleanup
 }
 
 #
@@ -462,14 +429,117 @@ install_npm_packages() {
     return 1
   fi
 
-  npm install -g "npm-check-updates"
-  npm install -g "yo"
-  npm install -g "jshint"
-  npm install -g "eslint"
-  npm install -g "grunt-cli"
-  npm install -g "gulp-cli"
-  npm install -g "autoprefixer"
-  npm install -g "node-sass"
+  typeset -a packages
+  packages=(
+    "npm-check-updates"
+    "yo"
+    "jshint"
+    "eslint"
+    "grunt-cli"
+    "gulpt-cli"
+    "autoprefixer"
+    "node-sass"
+  )
+
+  for name in "${packages[@]}"; do
+    npm install -g "$name"
+  done
+}
+
+#
+# Install macOS applications via the terminal.
+#
+# Usage: install_apps
+#
+install_apps() {
+  # Ensure cask is available
+  brew tap caskroom/cask
+  brew tap caskroom/fonts
+
+  # Install macOS applications via CASK
+  typeset -a casks
+  casks=(
+    "1password"
+    "alfred"
+    "bartender"
+    "dropbox"
+    "fluid"
+    "google-chrome"
+    "hazel"
+    "imagealpha"
+    "imageoptim"
+    "jadengeller-helium"
+    "mountain"
+    "slack"
+    "spotify"
+    "skyfonts"
+    "the-unarchiver"
+    "transmission"
+    "viscosity"
+    "visual-studio-code"
+    "virtualbox"
+  )
+
+  for name in "${casks[@]}"; do
+    brew cask install --appdir="~/Applications" "$name"
+  done
+
+  # Improve quicklook
+  typeset -a extensions
+  extensions=(
+    "qlcolorcode"
+    "qlmarkdown"
+    "qlstepen"
+  )
+
+  for name in "${extensions[@]}"; do
+    brew cask install "$name"
+  done
+
+  # Install some additional system fonts
+  typeset -a fonts
+  fonts=(
+    "open-sans"
+    "camingocode"
+    "source-code-pro"
+  )
+
+  for name in "${fonts[@]}"; do
+    brew cask install "font-$name"
+  done
+
+  # Launch Skyfonts to sync fonts via the service
+  find /usr/local/Caskroom/skyfonts -type d -name SkyFonts.app -exec open {} \;
+
+  # Reminder about applications that are licensed via the AppStore
+  typeset -a apps
+  apps=(
+    "Affinity Designer"
+    "Pixelmatator"
+    "iA Writer"
+    "Marked 2"
+    "Readkit"
+    "Dash 3"
+    "Yummy FTP Pro"
+    "Meta"
+    "Daisy Disk"
+    "ColorSnapper 2"
+    "Magnet"
+  )
+
+  print_status "You have licensed some of your applications via the AppStore:"
+  for name in "${apps[@]}"; do
+    printf "\t-%s" "$name"
+  done
+
+  seek_confirmation "Do you want to launch the AppStore now?"
+  if is_confirmed; then
+    open -a "App Store"
+  fi
+
+  # Cleanup downloaded packages
+  brew cask cleanup
+
 }
 
 #
@@ -512,31 +582,53 @@ main() {
   # Handle script options
   parse_options "$@"
 
-  # Install XCode on macOS
-  if is_mac && ! is_xcode_installed; then
-    print_warning "The XCode Command Line Tools must be installed first."
-    process_started "install_xcode" "Installing XCode Command Line Tools..."
-    if ! install_xcode; then
-      print_error "Could not install XCode Command Line Tools. Please install the Command Line Tools manually: https://developer.apple.com/downloads"
-      exit 1
-    fi
-    process_done "insall_xcode"
-  fi
-
   # Download and install the repository if not already done
   if ! install_dotfiles "$DOTFILES_REMOTE" "$DOTFILES"; then
     print_error "Could not install dotfiles."
     return 1
   fi
 
-  # Install frequently used homebrew formulae
-  if is_mac && [ "$INSTALL_FORMULAE" -eq 1 ]; then
-    process_started "install_homebrew_formulae" "Installing hombrew formulae..."
-    if ! install_homebrew_formulae; then
-      print_error "Could not install homebrew formulae."
-      return 1
+  if is_mac; then
+    # Install XCode on macOS
+    if ! is_xcode_installed; then
+      print_warning "The XCode Command Line Tools must be installed first."
+      process_started "install_xcode" "Installing XCode Command Line Tools..."
+      if ! install_xcode; then
+        print_error "Could not install XCode Command Line Tools. Please install the Command Line Tools manually: https://developer.apple.com/downloads"
+        exit 1
+      fi
+      process_done "insall_xcode"
     fi
-    process_done "install_homebrew_formulae"
+
+    # Install frequently used homebrew formulae
+    if [ "$INSTALL_FORMULAE" -eq 1 ]; then
+      process_started "install_homebrew_formulae" "Installing hombrew formulae..."
+      if ! install_homebrew_formulae; then
+        print_error "Could not install homebrew formulae."
+        return 1
+      fi
+      process_done "install_homebrew_formulae"
+    fi
+
+    # Install macOS applications
+    if [ "$INSTALL_APPS" -eq 1 ]; then
+      process_started "install_apps" "Installing macOS applications..."
+      install_apps
+      process_done "install_apps"
+    fi
+
+    # Run osxdefaults by Mathias Bynens
+    if [ "$UPDATE_OSX_SETTINGS" -eq 1 ]; then
+      seek_confirmation "Do you want to customize the OSX settings?"
+
+      if is_confirmed; then
+        process_started "osxdefaults" "Setting OSX defaults..."
+        sh "$DOTFILES/bin/osxdefaults"
+        process_done "osxdefaults"
+      else
+        process_aborted "osxdefaults"
+      fi
+    fi
   fi
 
   # Install frequently used npm packages
@@ -547,19 +639,6 @@ main() {
       return 1
     fi
     process_done "install_npm_packages"
-  fi
-
-  # Run osxdefaults by Mathias Bynens
-  if is_mac && [ "$UPDATE_OSX_SETTINGS" -eq 1 ]; then
-    seek_confirmation "Do you want to customize the OSX settings?"
-
-    if is_confirmed; then
-      process_started "osxdefaults" "Setting OSX defaults..."
-      sh "$DOTFILES/bin/osxdefaults"
-      process_done "osxdefaults"
-    else
-      process_aborted "osxdefaults"
-    fi
   fi
 
   # Create symbolic links if desired
