Added a function to the dotfiles script that displays submodules status

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,33 +1,23 @@
 #!/usr/bin/env bash
 
 #
-# Environment variables
+# Options/Flags
 #
 # $DOTFILES_DIRECTORY         = Path of the local working copy.
 # $DOTFILES_REMOTE_REPOSITORY = Name of the remote git repository.
+# $INSTALL_NPM_PACKAGES       = Install list of npm packages
+# $INSTALL_FORMULAE           = Install list of hombrew formulae
+# $CREATE_SYMLINKS            = Create symbolic links to dotfiles
+# $UPDATE_SUBMODULES          = Whether to update submodules or not
 #
 
-if [ -z "$DOTFILES_DIRECTORY" ]; then
-  DOTFILES_DIRECTORY="$HOME/.dotfiles"
-fi
-
-if [ -z "$DOTFILES_REMOTE_REPOSITORY" ]; then
-  DOTFILES_REMOTE_REPOSITORY="dweidner/dotfiles"
-fi
-
-#
-# Options/Flags
-#
-# $INSTALL_NPM_PACKAGES = Install list of npm packages
-# $INSTALL_FORMULAE     = Install list of hombrew formulae
-# $CREATE_SYMLINKS      = Create symbolic links to dotfiles
-# $UPDATE_SUBMODULES    = Whether to update submodules or not
-#
-
+DOTFILES_DIRECTORY="$HOME/.dotfiles"
+DOTFILES_REMOTE_REPOSITORY="dweidner/dotfiles"
 INSTALL_NPM_PACKAGES=0
 INSTALL_FORMULAE=0
 CREATE_SYMLINKS=0
 UPDATE_SUBMODULES=0
+UPDATE_OSX_SETTINGS=0
 
 #
 # Tells users how to use the script.
@@ -37,15 +27,15 @@ UPDATE_SUBMODULES=0
 usage() {
   cat <<EOT
 
-Usage: dotfiles [-h] [-l] [-u] [-s] [-b] [-n]
+Usage: dotfiles [-h] [-u] [-s] [-b] [-n] [-x] [-a]
 
 Options:
    -h  Print usage information.
-   -l  List submodules installed with the repository.
    -u  Update submodules installed with the repository.
    -s  Create symbolic links (may overwrite existing).
    -b  Install homebrew formulae.
    -n  Install npm packages.
+   -x  Run script to customize OSX default settings.
    -a  Combine options [-u], [-s], [-b] and [-n]
 
 Copyright (c) Daniel Weidner
@@ -83,9 +73,6 @@ parse_options() {
       -h) usage
           exit 0
           ;;
-      -l) list_submodules "$DOTFILES_DIRECTORY"
-          exit 0
-          ;;
       -u) UPDATE_SUBMODULES=1
           ;;
       -s) CREATE_SYMLINKS=1
@@ -94,7 +81,10 @@ parse_options() {
           ;;
       -n) INSTALL_NPM_PACKAGES=1
           ;;
+      -x) UPDATE_OSX_SETTINGS=1
+          ;;
       -a) UPDATE_SUBMODULES=1
+          UPDATE_OSX_SETTINGS=1
           CREATE_SYMLINKS=1
           INSTALL_FORMULAE=1
           INSTALL_NPM_PACKAGES=1
@@ -266,6 +256,116 @@ read_package_list() {
 }
 
 #
+# Determine how many commits the given working copy is ahead/behind
+# the upstream repository.
+#
+# Usage: get_upstream_status path
+#
+# $1 = Path to the working copy.
+#
+get_upstream_status() {
+  local dir="$1"
+
+  # Determine the status of the current repository compared to the upstream
+  local status=""
+  local count=""
+  count="$(git rev-list --count --left-right "@{upstream}"...HEAD 2>/dev/null)"
+
+  # Switch to the given directory
+  pushd "$dir" >/dev/null
+
+  # Interpret the result of
+  case "$count" in
+
+    # No upstream
+    "") status="?";;
+
+    # Equal
+    "0	0") status="=";;
+
+    # Ahead
+    "0	"*) status="+${count#0	}";;
+
+    # Behind
+    *"	0") status="-${count%	0}";;
+
+    # Diverged
+    *) status="+${count#*	}-${count%	*}";;
+
+  esac
+
+  # Switch back to the previous directory
+  popd >/dev/null
+
+  # Return the determined status
+  echo "$status"
+}
+
+#
+# Display the status of the dotfiles repository and all its submodules.
+# shellcheck disable=SC2032
+#
+# Usage: show_submodule_status name path toplevel
+#
+show_submodule_status() {
+  local path="$1"
+  local toplevel="$2"
+  local name="${path##*/}"
+  local status=""
+
+  status="$(get_upstream_status "$toplevel/$path")"
+
+  printf "%-6s %s\n" "$status" "$name"
+}
+
+#
+# Display the status of all submodules added to the dotfiles repository.
+#
+# Usage: show_status dir
+#
+# $1 = Path to the working tree.
+#
+show_status() {
+  local dir="$1"
+  local status=""
+  local pending_updates=0
+
+  # Switch to the given directory
+  pushd "$dir" >/dev/null
+
+  # Export internal functions so we can use them within the
+  # `git submodule foreach` loop
+  export -f show_submodule_status get_upstream_status
+
+  # Determine the status of each submodule.
+  # shellcheck disable=SC2016,SC2033
+  status="$(git submodule foreach --quiet --recursive 'echo "$path $toplevel"' | xargs -n2 -P20 sh -c 'show_submodule_status "$@"' show_submodule_status | grep -v "^=")"
+
+  # Remove the internal functions from the global scope
+  unset -f show_submodule_status get_upstream_status
+
+  # Switch back to the previous directory
+  popd >/dev/null
+
+  # Only show submodules which are behind the upstream
+  if [ -n "$status" ]; then
+
+    # Count the total number of modules that require an update
+    pending_updates="$(echo -ne "$status" | wc -l |  tr -d '[:space:]')"
+
+    # Summarize the modules with pending updates
+    if [ "$pending_updates" -gt 0 ]; then
+      printf "%s pending updates:\n%s\n\n" "$pending_updates" "$status"
+      return 0
+    fi
+
+  fi
+
+  printf "All submodules are up to date.\n\n"
+  return 0
+}
+
+#
 # Initialize a given directory as git repository.
 #
 # Usage: initialize_repository dir [remote]
@@ -293,18 +393,6 @@ initialize_repository() {
 
   # Switch back to the previous directory
   popd >/dev/null
-}
-
-#
-# Displays an overview of installed submodules.
-#
-# Usage: list_submodules dir
-#
-# $1 = Path of the working copy.
-#
-list_submodules() {
-  local dir="$1"
-  # TODO: Provide an overview of installed submodules
 }
 
 #
@@ -484,7 +572,6 @@ install_homebrew_formulae() {
 
   # Return the last exit code
   return $?
-
 }
 
 #
@@ -525,13 +612,10 @@ install_npm_packages() {
 
   # Return the last exit code
   return $?
-
 }
 
 #
 # Script entry point
-#
-# $1 = One of the supported options.
 #
 main() {
   # Render the script header
@@ -559,6 +643,19 @@ main() {
     return 1
   fi
 
+  # Update all dependencies added as submodules to the project
+  if [ "$UPDATE_SUBMODULES" -eq 1 ]; then
+    echo "Updating submodules..."
+    if ! update_submodules "$DOTFILES_DIRECTORY"; then
+      echo "ERROR: Could not update submodules."
+      return 1
+    fi
+    echo "Done."
+  fi
+
+  # Display the status of submodules added to the repository
+  show_status "$DOTFILES_DIRECTORY"
+
   # Create symbolic links if desired
   if [ "$CREATE_SYMLINKS" -eq 1 ]; then
     echo "Creating symbolic links..."
@@ -585,25 +682,17 @@ main() {
     echo "Done."
   fi
 
-  # Update all dependencies added as submodules to the project
-  if [ "$UPDATE_SUBMODULES" -eq 1 ]; then
-    echo "Updating submodules..."
-    if ! update_submodules "$DOTFILES_DIRECTORY"; then
-      echo "ERROR: Could not update submodules."
-      return 1
-    fi
-    echo "Done."
-  fi
-
   # Run osxdefaults by Mathias Bynens
-  seek_confirmation "Do you want to customize the OSX settings?"
+  if [ "$UPDATE_OSX_SETTINGS" -eq 1 ]; then
+    seek_confirmation "Do you want to customize the OSX settings?"
 
-  if is_confirmed; then
-    echo "Setting OSX defaults..."
-    bash "$DOTFILES_DIRECTORY/bin/osxdefaults"
-    echo "Done."
-  else
-    echo "Aborted."
+    if is_confirmed; then
+      echo "Setting OSX defaults..."
+      bash "$DOTFILES_DIRECTORY/bin/osxdefaults"
+      echo "Done."
+    else
+      echo "Aborted."
+    fi
   fi
 
   return 0
